# Generated by Django 4.0.2 on 2022-03-09 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawPokeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('data', models.JSONField()),
                ('fave', models.BooleanField(verbose_name=False)),
                ('evs', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_name', models.CharField(max_length=20)),
                ('evo_data', models.JSONField()),
                ('evo_tier', models.IntegerField(default=0)),
                ('poke_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.rawpokedata')),
            ],
        ),
    ]
